version: '3'

services:
  web-server:
    image: jojo-server-image1:latest
    depends_on:
      - database-server
    environment:
      POSTGRES_HOST: database-server
      POSTGRES_PORT: 5432
    env_file:
      - docker.env
    ports:
      - 8300:8300
  database-server:
    image: postgres:15.3-alpine3.18
    environment:
      POSTGRES_PORT: 5432
    env_file: docker.env
    ports:
      - 8432:5432
    volumes:
      - ./pgdata:/var/lib/postgres/data
